version: '3.8'
services:
  vsftpd:
    image: panubo/vsftpd
    environment: 
      - FTP_USER=prueba
      - FTP_PASSWORD=prueba
    volumes:
      - /mnt/storage/media:/srv
    expose:
      - 21
    network_mode: host